spring:
  application:
           name: cloudgateway

server:
     port: 8088
     
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    
spring:
  cloud:
    gateway:
      routes:
        - id: employeeAPI
          uri: lb://employee-api
          predicates:
            - Path=/empapi/**
          filters:
            - RewritePath=/employee/(?<path>.*), /$\{path}
