spring:
  application:
           name: cloudgateway
  cloud:
    gateway:
      routes:
        - id: booksAPI
          uri: lb://BOOK-SERVICE
          predicates:
          - Path=/booksapi/**
          filters:
          - RewritePath=/booksapi(?<segment>/?.*), /books$\{segment}

server:
     port: 8088
     
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
