spring:
  application:
           name: cloudgateway

server:
     port: 8088
     
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    
spring:
  cloud:
    gateway:
      routes:
        - id: booksAPI
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/booksapi/**
          filters:
            - RewritePath=/books/(?<path>.*), /$\{path}
